typography_spectrum: 0.37371243443340063
content_rating:
  adult: false
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.25
github: true
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.3031243160367012
analytics:
  google: UA-58965710-2
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  url: ''
  email: pierre.sottas@cheesecom.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7db79d5-805b-4626-bd56-09aca8133347.jpg
name: Espresso From Hell
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact
    id: 8bc87754-9321-465b-a461-5509dab72181
    type: content
  - name: Presskit
    url: 'http://presskit.espressofromhell.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0e4f9ca4-6439-4b10-87ef-a648cf5f670f.jpg
title: Espresso From Hell
content: []
description: Electro-Jazz from Switzerland
purpose:
  - type: external
    url: 'http://presskit.espressofromhell.com'
    label: Presskit
  - type: contact
    url: 'mailto:booking@espressofromhell.com'
    label: Book us!
