layout_spectrum: 0.03470736147928061
typography_spectrum: 0.06547506568473901
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.09024296892207521
  lightness: 0.3003560107607062
  saturation: 0.05953358436685683
  rhythmicContrast: 0.9945662424642371
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: ''
  appId: ''
analytics:
  google: UA-58965710-2
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  url: ''
  email: pierre.sottas@cheesecom.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7db79d5-805b-4626-bd56-09aca8133347.jpg
name: Espresso From Hell
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The Band
    id: fa1dda74-fde8-4b63-bfc9-3e0b1f340a72
    type: content
  - name: Contact
    id: 8bc87754-9321-465b-a461-5509dab72181
    type: content
  - name: What guys say
    id: f6747690-a48e-4ef4-8832-e3156fb4feff
    type: content
  - name: Presskit
    url: 'http://presskit.espressofromhell.com'
    type: external
  - name: Pictures
    id: 0bed4426-3ddb-467a-b543-49e9950a89fe
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0e4f9ca4-6439-4b10-87ef-a648cf5f670f.jpg
title: Espresso From Hell
content: []
description: Electro-Jazz from Switzerland
purpose:
  - type: external
    url: 'http://presskit.espressofromhell.com'
    label: Presskit
  - type: contact
    url: 'mailto:booking@espressofromhell.com'
    label: Book us!
